name: "Feature Request"
description: "Suggest a new feature or enhancement for the SSPR-UserManagement script"
title: "[Feature] "
labels: ["feature request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        Thank you for helping improve **SSPR-UserManagement**!  
        Please provide as much detail as possible so we can understand your idea.  
        **Required:** Keep the `[Feature]` prefix in the title for clarity.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A short, clear summary of your feature request.
      placeholder: "Example: Add support for exporting results to CSV"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detailed Description
      description: Explain why this feature would be useful and how you envision it working.
      placeholder: |
        Describe your idea in detail:
        - What problem does it solve?
        - How should the script behave?
        - Example: Add a `-ExportCsv` switch to save output automatically
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Optional – Have you considered any alternative approaches or workarounds?
      placeholder: |
        Example:
        - Manually run `Export-Csv` after script execution
        - Maintain a separate log file for tracking changes
